language: node_js
node_js:
  - lts/*

sudo: false

cache:
  directories:
    - "node_modules"

script:
  - npm test

after_success:
  - npm build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: build
  on:
    branch:
      - master
      - dev